### ISSUE TITLE
Rounding

### ISSUE THREAD

**Issue by nickto** [Rchieve/732A94_Lab6#1]
Answers correspond to the ones in the assignment (both for brute force and dynamic) only if we round the values. But it is never said in the assignment that we should do that. So, should we?

**Comment by torda385** [comment]
I think the rounding in the assignment comes from rounding in the knitr code.  I'd imagine whoever wrote the lab had a round() setting somewhere... I wouldn't worry too much about it.

**Comment by torda385** [comment]
For now, I have implemented round() in the following way.
expect_equal(round(knapsack_dynamic(x = knapsack_objects[1:12,], W = 2000)$value,2), 
               15427.81)

**Comment by nickto** [comment]
For consistency, we might also want to remove rounding here: https://github.com/Rchieve/732A94_Lab6/blob/master/R/knapsack_brute_force.R (line 43)

**Comment by nickto** [comment]
Removed rounding from the function. Added rounding to the tests.
